homework 4 pandas
uploaded manually because I'm having issues uploading jupyter notebooks? I'm able to force push it to GitHub but then it deletes all my other uploads

it gives me this error: 

error: failed to push some refs to 'ssh://git@github.com/abigailjmiller/BIOL_792_II.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.